### ISSUE TITLE
Document how to build and run my own copy

### ISSUE THREAD

**Issue by cloudrac3r** [caphindsight/TrulyQuantumChess#15]
I want to "download, build & run your local mongodb and webapp server" as suggested in the readme, but I have no idea how to build C#, and I'm really struggling to find out information about it online. It would be great if you added a summary of the steps needed to build the project on some operating system, and then I can do my best to make it work from there.

**Comment by llama-0** [comment]
@cloudrac3r Hello. You can clone the project, go to repository folder and type these two commands:
```
docker build -t chess .
docker run -p 9000:9000 -t chess
```
The first one builds an image from the Dockerfile (`-t chess` stands for --tag image_name), the second runs this image on port 9000 (-p 9000:9000 binds port 9000 on your machine with port 9000 on "image machine")

Now you should be able to access TrulyQuantumChess start page on localhost:9000

*Of course, your need docker to be installed on your machine (the easiest way is to install Docker App and run it. Then perform the steps mentioned above)

**Comment by cloudrac3r** [comment]
Thank you!

**Comment by cloudrac3r** [comment]
Hmm. I see the start page on localhost:9000, and I managed to disable the captcha, but after I press launch new game it looks like it has problems trying to connect to mongo.

I see this in the browser network logs:

    {"statusCode":500,"message":"Something went horribly, horribly wrong while servicing your request.","details":"Nancy.RequestExecutionException: Oh noes! ---\u003e System.TypeInitializationException: The type initializer for \u0027TrulyQuantumChess.WebApp.WebAppManagers\u0027 threw an exception. ---\u003e System.AggregateException: One or more errors occurred. (A timeout occured after 30000ms selecting a server using CompositeServerSelector{ Selectors = ReadPreferenceServerSelector{ ReadPreference = { Mode : Primary } }, LatencyLimitingServerSelector{ AllowedLatencyRange = 00:00:00.0150000 } }. Client view of cluster state is { ClusterId : \"1\", ConnectionMode : \"Automatic\", Type : \"Unknown\", State : \"Disconnected\", Servers : [{ ServerId: \"{ ClusterId : 1, EndPoint : \"127.0.0.1:27017\" }\", EndPoint: \"127.0.0.1:27017\", State: \"Disconnected\", Type: \"Unknown\", HeartbeatException: \"MongoDB.Driver.MongoConnectionException: An exception occurred while opening a connection to the server. ---\u003e System.Net.Sockets.SocketException: Connection refused\n  at System.Net.Sockets.SocketAsyncResult.CheckIfThrowDelayedException () [0x00014] in \u003c4d8f95b7df544b3fa1a27dda924b4424\u003e:0 \n  at System.Net.Sockets.Socket.EndConnect (System.IAsyncResult asyncResult) [0x0002c] in \u003c4d8f95b7df544b3fa1a27dda924b4424\u003e:0 \n  at System.Threading.Tasks.TaskFactory`1[TResult].FromAsyncCoreLogic (System.IAsyncResult iar, System.Func`2[T,TResult] endFunction, System.Action`1[T] endAction, System.Threading.Tasks.Task`1[TResult] promise, System.Boolean requiresSynchronization) [0x00019] in \u003cc453bf849bb84e719dbec0475e99db95\u003e:0 \n--- End of stack trace from previous location where exception was thrown ---\n\n  at MongoDB.Driver.Core.Connections.TcpStreamFactory.ConnectAsync (System.Net.Sockets.Socket socket, System.Net.EndPoint endPoint, System.Threading.CancellationToken cancellationToken) [0x0025a] in \u003c9cc50b9540454405a55b3515e4f48ce9\u003e:0 \n  at MongoDB.Driver.Core.Connections.TcpStreamFactory.CreateStreamAsync (System.Net.EndPoint endPoint, System.Threading.CancellationToken cancellationToken) [0x00092] in \u003c9cc50b9540454405a55b3515e4f48ce9\u003e:0 \n  at MongoDB.Driver.Core.Connections.BinaryConnection.OpenHelperAsync (System.Threading.CancellationToken cancellationToken) [0x000c8] in \u003c9cc50b9540454405a55b3515e4f48ce9\u003e:0 \n   --- End of inner exception stack trace ---\n  at MongoDB.Driver.Core.Connections.BinaryConnection.OpenHelperAsync (System.Threading.CancellationToken cancellationToken) [0x001da] in \u003c9cc50b9540454405a55b3515e4f48ce9\u003e:0 \n  at MongoDB.Driver.Core.Servers.ServerMonitor.HeartbeatAsync (System.Threading.CancellationToken cancellationToken) [0x000e7] in \u003c9cc50b9540454405a55b3515e4f48ce9\u003e:0 \" }] }.) ---\u003e System.TimeoutException: A timeout occured after 30000ms selecting a server using CompositeServerSelector{ Selectors = ReadPreferenceServerSelector{ ReadPreference = { Mode : Primary } }, LatencyLimitingServerSelector{ AllowedLatencyRange = 00:00:00.0150000 } }. Client view of cluster state is { ClusterId : \"1\", ConnectionMode : \"Automatic\", Type : \"Unknown\", State : \"Disconnected\", Servers : [{ ServerId: \"{ ClusterId : 1, EndPoint : \"127.0.0.1:27017\" }\", EndPoint: \"127.0.0.1:27017\", State: \"Disconnected\", Type: \"Unknown\", HeartbeatException: \"MongoDB.Driver.MongoConnectionException: An exception occurred while opening a connection to the server. ---\u003e System.Net.Sockets.SocketException: Connection refused\n  at System.Net.Sockets.SocketAsyncResult.CheckIfThrowDelayedException () [0x00014] in \u003c4d8f95b7df544b3fa1a27dda924b4424\u003e:0 \n  at System.Net.Sockets.Socket.EndConnect (System.IAsyncResult asyncResult) [0x0002c] in \u003c4d8f95b7df544b3fa1a27dda924b4424\u003e:0 \n  at System.Threading.Tasks.TaskFactory`1[TResult].FromAsyncCoreLogic (System.IAsyncResult iar, System.Func`2[T,TResult] endFunction, System.Action`1[T] endAction, System.Threading.Tasks.Task`1[TResult] promise, System.Boolean requiresSynchronization) [0x00019] in \u003cc453bf849bb84e719dbec0475e99db95\u003e:0 \n--- End of stack trace from previous location where exception was thrown ---\n\n  at MongoDB.Driver.Core.Connections.TcpStreamFactory.ConnectAsync (System.Net.Sockets.Socket socket, System.Net.EndPoint endPoint, System.Threading.CancellationToken cancellationToken) [0x0025a] in \u003c9cc50b9540454405a55b3515e4f48ce9\u003e:0 \n  at MongoDB.Driver.Core.Connections.TcpStreamFactory.CreateStreamAsync (System.Net.EndPoint endPoint, System.Threading.CancellationToken cancellationToken) [0x00092] in \u003c9cc50b9540454405a55b3515e4f48ce9\u003e:0 \n  at MongoDB.Driver.Core.Connections.BinaryConnection.OpenHelperAsync (System.Threading.CancellationToken cancellationToken) [0x000c8] in \u003c9cc50b9540454405a55b3515e4f48ce9\u003e:0 \n   --- End of inner exception stack trace ---\n  at MongoDB.Driver.Core.Connections.BinaryConnection.OpenHelperAsync (System.Threading.CancellationToken cancellationToken) [0x001da] in \u003c9cc50b9540454405a55b3515e4f48ce9\u003e:0 \n  at MongoDB.Driver.Core.Servers.ServerMonitor.HeartbeatAsync (System.Threading.CancellationToken cancellationToken) [0x000e7] in \u003c9cc50b9540454405a55b3515e4f48ce9\u003e:0 \" }] }.\n  at MongoDB.Driver.Core.Clusters.Cluster.ThrowTimeoutException (MongoDB.Driver.Core.Clusters.ServerSelectors.IServerSelector selector, MongoDB.Driver.Core.Clusters.ClusterDescription description) [0x00013] in \u003c9cc50b9540454405a55b3515e4f48ce9\u003e:0 \n  at MongoDB.Driver.Core.Clusters.Cluster+WaitForDescriptionChangedHelper.HandleCompletedTask (System.Threading.Tasks.Task completedTask) [0x00009] in \u003c9cc50b9540454405a55b3515e4f48ce9\u003e:0 \n  at MongoDB.Driver.Core.Clusters.Cluster.WaitForDescriptionChangedAsync (MongoDB.Driver.Core.Clusters.ServerSelectors.IServerSelector selector, MongoDB.Driver.Core.Clusters.ClusterDescription description, System.Threading.Tasks.Task descriptionChangedTask, System.TimeSpan timeout, System.Threading.CancellationToken cancellationToken) [0x000b4] in \u003c9cc50b9540454405a55b3515e4f48ce9\u003e:0 \n  at MongoDB.Driver.Core.Clusters.Cluster.SelectServerAsync (MongoDB.Driver.Core.Clusters.ServerSelectors.IServerSelector selector, System.Threading.CancellationToken cancellationToken) [0x00120] in \u003c9cc50b9540454405a55b3515e4f48ce9\u003e:0 \n  at MongoDB.Driver.Core.Bindings.ReadPreferenceBinding.GetReadChannelSourceAsync (System.Threading.CancellationToken cancellationToken) [0x0008b] in \u003c9cc50b9540454405a55b3515e4f48ce9\u003e:0 \n  at MongoDB.Driver.Core.Operations.ReadCommandOperation`1[TCommandResult].ExecuteAsync (MongoDB.Driver.Core.Bindings.IReadBinding binding, System.Threading.CancellationToken cancellationToken) [0x0009e] in \u003c9cc50b9540454405a55b3515e4f48ce9\u003e:0 \n  at MongoDB.Driver.OperationExecutor.ExecuteReadOperationAsync[TResult] (MongoDB.Driver.Core.Bindings.IReadBinding binding, MongoDB.Driver.Core.Operations.IReadOperation`1[TResult] operation, System.Threading.CancellationToken cancellationToken) [0x00075] in \u003cf610437d1b274073afaed44e3908ccaf\u003e:0 \n  at MongoDB.Driver.MongoDatabaseImpl.ExecuteReadOperationAsync[T] (MongoDB.Driver.Core.Operations.IReadOperation`1[TResult] operation, MongoDB.Driver.ReadPreference readPreference, System.Threading.CancellationToken cancellationToken) [0x000a0] in \u003cf610437d1b274073afaed44e3908ccaf\u003e:0 \n   --- End of inner exception stack trace ---\n  at System.Threading.Tasks.Task.ThrowIfExceptional (System.Boolean includeTaskCanceledExceptions) [0x00011] in \u003cc453bf849bb84e719dbec0475e99db95\u003e:0 \n  at System.Threading.Tasks.Task.Wait (System.Int32 millisecondsTimeout, System.Threading.CancellationToken cancellationToken) [0x00043] in \u003cc453bf849bb84e719dbec0475e99db95\u003e:0 \n  at System.Threading.Tasks.Task.Wait () [0x00000] in \u003cc453bf849bb84e719dbec0475e99db95\u003e:0 \n  at TrulyQuantumChess.WebApp.MongoManager..ctor () [0x0006a] in \u003c44c32ca3d4a744afb8256b3fb497e15d\u003e:0 \n  at TrulyQuantumChess.WebApp.WebAppManagers..cctor () [0x00000] in \u003c44c32ca3d4a744afb8256b3fb497e15d\u003e:0 \n   --- End of inner exception stack trace ---\n  at TrulyQuantumChess.WebApp.ApiModule.NewGame (System.Object args, System.Threading.CancellationToken cancellation_token) [0x002f5] in \u003c44c32ca3d4a744afb8256b3fb497e15d\u003e:0 \n   --- End of inner exception stack trace ---\n  at Nancy.NancyEngine.InvokeOnErrorHook (Nancy.NancyContext context, Nancy.ErrorPipeline pipeline, System.Exception ex) [0x000bd] in \u003c63c44d6f8d7e4f339a987bf9eb94d931\u003e:0 "}

My key takeaway is this: `A timeout occured after 30000ms selecting a server`

I assume that this is caused because mongo isn't running, or because it couldn't detect mongo. Do I need to run mongo on my own, outside of docker? But I thought the point of docker was that things can't get out of their containers...?

**Comment by llama-0** [comment]
@cloudrac3r Well, I do not know how to do it properly, but I came up with a workaround.

1. Create a file `docker-compose.yml` with the following contents:
```
version: '3'
services:
  web:
    image: chess
    build: .
    command: "mono WebApp.exe"
    ports:
      - "9000:9000"
    depends_on:
      - "mongo"
  mongo:
    image: "mongo"
    ports:
      - "27017:27017"
```
*Be sure to use spaces instead of tabs or you'll probably get a syntax error.

2. make changes to `WebAppConfig_dockerized.json` at line 5:
replace `mongodb://mongo.storage.hindsight.hindsight.node.intern` with `mongodb://mongo:27017`

3. Launch like this:
```
docker-compose build
docker-compose up
```

Now after every change you make to the project step 3 will be how you build & run it.

**Comment by cloudrac3r** [comment]
Yes, it seems to work now! Thank you so much! I was trying to do something similar but I didn't know docker well enough to pull it off.

**Comment by llama-0** [comment]
You are welcome :)

**Comment by caphindsight** [comment]
FYI, if you add the `docker-compose.yml` file and/or update the README with these instructions, I will happily approve the pull request.

**Comment by cloudrac3r** [comment]
I'm away from home right now. I may be able to do this in a few days.
